import { Command } from "commander";
import CommandGenerteTemplate from "./generate-template";
import CommandGeneratePBETemplate from "./generate-pbe-template";
import CommandReport from "./report";
import CommandSendMessage from "./send-message";
import CommandSendPBEMessage from "./send-pbe-message";
import CommandFixMessage from "./fix-message";
import CommandTestSouffle from "./test-souffle";
import CommandTestPBE from "./test-pbe";

const program = new Command("chatalog");
program.addCommand(CommandGenerteTemplate);
program.addCommand(CommandGeneratePBETemplate);
program.addCommand(CommandSendMessage);
program.addCommand(CommandSendPBEMessage);
program.addCommand(CommandFixMessage);
program.addCommand(CommandTestSouffle);
program.addCommand(CommandTestPBE);
program.addCommand(CommandReport);
program.parse();
